/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed-dim": "#ffb596",
        "on-surface-variant": "#434655",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d3e4fe",
        "error-container": "#ffdad6",
        "outline": "#737686",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed": "#360f00",
        "secondary-fixed": "#ffdbca",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "secondary-container": "#fd761a",
        "surface-tint": "#0053db",
        "on-secondary-container": "#5c2400",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#eeefff",
        "inverse-surface": "#213145",
        "surface": "#f8f9ff",
        "on-primary-fixed-variant": "#003ea8",
        "background": "#f8f9ff",
        "tertiary": "#943700",
        "outline-variant": "#c3c6d7",
        "tertiary-container": "#bc4800",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#783200",
        "inverse-primary": "#b4c5ff",
        "secondary": "#9d4300",
        "on-background": "#0b1c30",
        "tertiary-fixed": "#ffdbcd",
        "primary-container": "#2563eb",
        "primary-fixed-dim": "#b4c5ff",
        "primary": "#004ac6",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed": "#00174b",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed": "#341100",
        "on-tertiary-container": "#ffede6",
        "secondary-fixed-dim": "#ffb690",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "unit": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "stack-sm": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "title-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "title-md": ["18px", { "lineHeight": "1.5", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
